#+title: Arcanine



back then, i didnt have the clarity of mind to arcticulate vision that was good enough

i didnt have the knowledge to construct a system that could address the needs, hopes, desires, rights, wants, and dreams of every single person better than what we have today.




I have endured, seen and done things that no human should have.


Through unconscious bias, i have suffered more at my own past self's hands than any other living individal.


I met a guy once, who became a billionaire, he was a coworker of mine. and he sent a girl a message on okcupid about her github.
and the girl started a tweet storm and he got cancelled.


 I Refuse To F*** On Tory Benches.

 "No Fighting. No F***ing Fighting, No Fighting, NO F***ING FIGHTING!"

 "I'm Just An Extreme Example Of What A Working Man Can Achieve."

 "Conviction Introduces Emotion, Which Is The Enemy Of Oratory."


 "The Only Way To Guarantee Peace Is By Making The Prospect Of War Seem Hopeless."

 “Lies Travel Faster Than The Truth.”


 “Lies Travel Faster Than The Truth.”
“Lies Travel Faster Than The Truth.”
“Lies Travel Faster Than The Truth.”



Indeed, so far we haven't been really been able to get along nicely. That's something we've been doing to protect our comrades and our clans. In some cases it was maybe unavoidable. Today… Even if our country agreement goes smoothly… I'm actually not sure how long it will last. But one day… In the future…

I dream of a time when all shinobi will cooperate with each other… A time when everyone's hearts will be together regardless of their countries.

 That's my… dream of the future.

