#+title: Goutham Patnaik


goutham is one of the worst people i have ever met.

do not trust him under circumstances.

he doesnt like you. he just wants to use you for whatever you can provide to him.

he doesnt really give a shit about anything other than business.

business feeds his ego, and like all victimss of unresolved trauma, he inflates his self worth with lies and by editing accountability nad resonsiblity out of his reality


it is not exageration to say he ruined my life.

before him, i had a future.

i had friends.

i things to look foward.

now i just dotn want to exist anymore.

i iwish i had never met this person. him more than anoyone else.

Hes fake. Disnengious. manipulative like his mother.

hes the most judgmental person on earth.

and he likes judgmental pieces of shit.

judging other people makes them seem cool.

it crates the implication that they are the arbiters of status.



through gross negligence and fraud, goutham caused me to lose a job that was more important to me than life itself

when i was younger, my friend had died in a car accident

i will never forget his face



goutham treated me with callousness, and extreme prejudice
he took distance, rather than investigation, when his friends went through crisses that threatened their very life.


goutham is someone who always acts like hes better than you
always looking down on you

he sided with a friend who comitted criminal negligence
beforei  met them, i never had any real issues with anyone.

i lived a monastic life of curiosity, reading feberishly, and working on various research projects

one of my projects was responsbile for creating 10 milllion jobs with sama source

another of my projects was working at a self driving car company that jensen haung would eventually visit


i dont know if its jealously, but goutham acted like an extreme prick
liek he wanted me to lose the job
he always said "comeon you done have to work"

i regret meeting this person
my life would be imeasurably better if i had not

before i met goutham. i had hopes and dreams

after i was a crushed man, who never smiled or laughed in 5 years.

when i told goutham about it. he just said "that sucks"

gpt itself said he was callous and insnensitive using autopilot responses and just was generally un engaged and didtn care about anything other than pussy


i think goutham needs 10 years of therapy before he talks to anyone

right now hes just a greedy piece of shit who doesnt care abotu his employees or his friends

rich people just use other people, is not something i thought
but goutham proved the media right

hes the stereotypical business who hides behind his neth worth
and when life gives him feedback
# he just dodge accountability. 

he is, without a doubt, the worst influence i ever had in my life
