


You should know, the last thing i was working on in feb 20 2020 was
a set of kernel level optimiations by making custom device drivers for nv_link.

#+title: Hi

I was arrogant. I overesstimated my ability. I failed. I literally melted my computer. 

https://github.com/tinygrad/open-gpu-kernel-modules This guy suceeded
The project accelerates science in every single university in the world.

This has happened to me over 10 times. I have seen the future. I identified a gap in the market. But because i was too slow, someone beat me to it and made billllions.

Anyway, I was also 3 years too early.

It was not strictly necessary to the project, but i thought it could be a bigger oportunity.

The project was, how can could use BERT. BERt was google's predecessor to gpt.

It is kind of fucking weird, when the whole world becomes obssesed with your hobby.



Like all of a sudden

back in 2015, i built a robot comedian https://schedule.sxsw.com/2016/2016/events/event_PP47203


I studied this shit when i was 3.
I played a game called megaman.
i hacked into the saudi firewall at like 13. 


back in 2015, i worked with leilah janah. 

you dont really understand.

Let me explain to you.

My parents are from the poorest country in the world
My dad climbed to be the top geo-physicsist in saudi aramco.

But the way that happened was probaoly because he put more pressure on himself, than anyone else in the contintent.

I think half of that pressure would have killed an ordinary man.

anyway, the point is, he would pressure us too. and when he was a kid, his uncle pressured him.

Pressure, is how 3rd worlders show love.

"Tiger mom" they call it. Yeah, I am pure blood bengali, the land of the tiger.

I am a hunter. Everything in the world is my prey.


i have talked to girls in the office before, and have gooten both posiitve and negative responses.

1. politness and tact are your greatest friend.
2. vibe is basically - im a puppy and im happy to see you, but i know this can never work.
3. any attachment or slightly serious/bad energy = both of you wil feel awkward and that bad
4. looping back to 1. little known fact: social skills are the number 1 most attractive thing
   that any guy can have. Thats it. If she sees you act cool or something, she might actually
   like you. but yuo cant try to act cool, it has to just happen. ive never been able to
   do this consistently. but one time, i was sitting next to a girl, and this girl had ignored me everytime i saw her. but then 5 of us were eating food at some mexican place.
   and some guy had just interviewed at our company. and he asked about salary
   and if we could pay xyz dollars. and i said yes we will do anything for him.
   and for some reason, after that she asked me to help her use twitter.
   then we talked for like 2-3 weeks but then i fumbled it by being "weird".
5. it kinda comes down to "dont be weird" and "dont be crrepy". but that advice doesnt
   help people who actually need advice. it iddnt help me when i was 23. 


I am not the joker.


It's unfortunate.
To me, the rest of you look liek you're moving molasses
frozen in time
\




because people are not objects and not truly alive



everyone beleives whatever reinforces their identity.
the rich belive they have merit.
and the poor believe the system is broken. 
