#+title: My Ultimate Wish

i dream of a world where muslims and jews, ukranians and russians all work together in harmony

i dont believe in good and evil.

When i was 7, i read the book "master and the marghita" by mikhail bulgakov

Theres a scence where pontius pilate talks to yeshua of nazareth

he says "there are no bad peopel in this world"

what about the rapist?

"if i had just a few minutes of time with him, he would understand and he would change his ways"

as a 2nd grader, this had a deep impact on me.

Later i read about eugene V debbs

AFter taking lsd more than 300 times, i no longer see people as good or bad.

i just see them as parts of me.

Some people are my asshole. Some people are the crown chakra. Some people are the visual cortex.

But invariably, i do not see any as better or worse in any way at all.

They are all chain reactions. Consequences of causality.


I see them more like cats and dogs.

You cant dislike a dog. its cute no matter what it does.

even if it has rabies. even if it tries to kill you. i'd gladly accept death, even if it was old yeller.

the point is. our identies are not real

but our identities drive our actions.

its so boring.

ive been waiting for the world to catch up for 30 years.

ive decciede the only way to unite the world

is to create a greater scope enemy

if no enemey exists

i will become that enemey.

