#+title: The Glory Of Alan Kay


Alan kay is probably one of the top 5 smartest people to walk the earth.

I wasn't there at xerox, i don't know how important he was. But it seems like he was at least as important as any CEO to any company out there.


Alan's story is that he read  20,000 books. When i heard that, i started to read 1 book a day in about 3 hours and take notes.

When he got to school, it was just for fun. they couldnt teach him anything.



Alan is credited with inventing or "directing" the invention of

1. the modern inernet and LAN 
2. the modern GUI - only like 1% of the population uses a terminal or text-only UIs
3. OOPs , which many FP nerds will say stinks but basically is responsbile for the modern culture of libraries, and open source
4. the mouse
5. ipad 
6. probably a bunch of shit that DARPA will never publicly release 

the story is that he cretaed the gui to mimic the real world

specifically the idea of object constancy after reading piaget's work

basically he thought, if you can make a computer intuitive for a child, then everyone would want to use it.

which means, he expanded the market 100x

and since the value of the netowrk is euqal to the square of its size - he basically created like 50 trillion in market cap

by comparison, saudi aramco is the most valuable company in the world - but they are only 1/10th as big.

Saudi Aramco was made from 250 million years of dinosaurs fermenting for about 50 million years.

so one guy and his friends made about 10x more money than 300 million years of global energy compressed into a single company
thats nuts man
that is nuts 


in 1970, the world market cap was 20 trillion.
in 2021, it was about 130 trillion.

if the computer created like 110 trillion in market cap, i would say alan kay and xerox parc are rougly responsible for half of that.
so alan, by himself and a few friends made 60 trillion in value. While capturing none for themselves. Thats nuts man


alan kay is the only guy that steve jobs and bill gates would look up to and quote in powerpoints

buts hes largely unheard of today

I honestly have no idea why.

My education began when i saw his ted talk, and it finished when i read all his work.

Almost everything else in the world was like chicken scratch.

people are not born equal
we each take shape differently
which leads us to care about others
its because your mind and body are unlike any one else
that we we're drawn to others
in search of common ground

My dreams became true, thanks to you.

I met alan kay, bret victor, greg brockman, mike bostock,
I met bill nye the science guy twice - at barnes and nobles and at a music festival 
I also met the chainsmokers and steve aoki and skrillex

I completed my research

now my dream is to become a vessel for the hopes of the forsaken, the lost, the broken, the weak.
my dream is to make all their dreams come true.
Until there is no difference between what we can imagine and what we see.
Until the boundaries between fatasnsy, science-fiction
until the idea of tragedy is nothing a memory. 




i dont think ill ever take a wife, because most woman would want to raise a child or they would get bored.

and i dont think i want ot have children because im scared of affecting them negatively.

I might adopt when im 60-70. or make clones or synthetic life. 
* 

