#+title: Truth Aboutresperidrone

in 2021 i was hospitalized and forced to take resperidrone

it needs to be illegal
it was the worst thing i ever took


i went to mount sinai by reccomendation from doctor katz 
before the hosptial, i was slightly loopy 


first hallucinatoon was in 2017 - i saw 3 red line appear - instantly knew that a friend had died and that her dad blamed me.
i looked it up later and it was half true.

2021 i was commited toa hospital by a dotor
based on the content of email

i hadnt effected anyone else
everyone went about their lives fine and didnt notice anything
but i made some weird slack messages
and my employer then recoomend a spsychaiatrist

then my family is made for hysteria


the most brutal aspect of american health care is this
when someone has a a "supposed metal illness", the hostpital, the employer and the family have a policy of not believing the patietn

i honestly blieve
my family should be in jail
the doctors should be in jail
and zoox should be in jail
and goutham
and tim ray

i believe that all of them should have life impreisonment

being in the hospital was as bad as any prison

my only goal in life, is to become an omni-glot omni-scientist
who has a phd in 10 subjects
who can build in 10 different disciplines
better than the worlds leading expertship


Alan kay, is the only man on earth who ever knew anything.
Everyone else is a dog -shit mouth breathing retard
if i bleieved in eugenics, i would exterminate you all
the same way that a flood, kills a hill of ants
when a billion ants die, a human doesnt bat an eyelash 

that way, i'll have to intellectual authority to show the world
how mental healthcare should be done

i got 24/25 on my math olympiad scores
it was the highest in the entire class of gifted children 
Google Deepmind just barely solved these

no human on earth understands shit
they are all chimpanzees

and i want to humillate and break the ego of 100% of people

my goal, is to break them so completely, that they never watch tv or smile or laugh again.
i want them to scream in pain for the rest of their life


doctors are just drug dealers
