#+title: Truth Aboutresperidrone

in 2021 i was hospitalized and forced to take resperidrone

it needs to be illegal
it was the worst thing i ever took

they used to lobotomize people

they used to stick needles above their eye, in the socket, and twirl it around until the patients brain was mashed potatos.
This would "solve" the problem where the patient might hurt someone about 1 time in 100.

Most schizophrnic patients are overwhelmingly not violent. 90% are not. But the stigma is there.
New york is insaenly regressive in their policies but especially related to mental health.
Especially related to anything that controls the population, like a herd of animals
at that scale, of 8 million, thats the only paradigm that functions in previous society
because they lacked the tools and scietnfici understanding to be effective

I feel bad for doctors. They are using woefully inadequate tools.

I think doctors are heroes. One and all. They all study hard. They could make more money in ANY other profression.

Doctors are a victim here, almost as bad as patients. ALmost as bad as society.

If john nash took risperdrone, he would not be able to do nobel prize winning work.
The medicaiton he was on took about 10-15 years from him.

The benefit of game theory is that it runs google's ad network. The theory lets them generate 300billion in revenue with
next to no margins.
Without nash, that probably wouldnt happen. There'd be google.

We don't how many googles there could be, if we treated the people who are the most "different" and "unique"
in ways that it takes the economy sometimes two decades to truly undertstand and reward.


It took me 4 years to recover, if ever at all. In fact, i only say 4, because i dont remember what its like to be normal
risperidrone robbed me of that possiblity.
in 2019, i could fake it, by just not saying much.
but now i cant.

i was institutionalized in 2021.
in 2022, i was 50% recovered after a year. I stil lcouldnt use the sauna for longer than 5 minutes.
It basically created a loss in executive function, which is probably the most useful predictor and cause of sucess.


in 2023, i was 75% recovered. In 2024, i am now 90%.
hope next year its around 95 but it feels like it will just be stuck at 90% permanently.


Risperidrone can lower white matter density by 25% after just a year of treatment.

When its used in monkeys, it renders them comatose. 




i went to mount sinai by reccomendation from doctor katz 
before the hosptial, i was slightly loopy 


first hallucinatoon was in 2017 - i saw 3 red line appear - instantly knew that a friend had died and that her dad blamed me.
i looked it up later and it was half true.

2021 i was commited toa hospital by a dotor
based on the content of email

i hadnt effected anyone else
everyone went about their lives fine and didnt notice anything
but i made some weird slack messages
and my employer then recoomend a spsychaiatrist

then my family is made for hysteria


the most brutal aspect of american health care is this
when someone has a a "supposed metal illness", the hostpital, the employer and the family have a policy of not believing the patietn

i honestly blieve
my family should be in jail
the doctors should be in jail
and zoox should be in jail
and goutham
and tim ray

i believe that all of them should have life impreisonment

being in the hospital was as bad as any prison

my only goal in life, is to become an omni-glot omni-scientist
who has a phd in 10 subjects
who can build in 10 different disciplines
better than the worlds leading expertship


Alan kay, is the only man on earth who ever knew anything.
Everyone else is a dog -shit mouth breathing retard
if i bleieved in eugenics, i would exterminate you all
the same way that a flood, kills a hill of ants
when a billion ants die, a human doesnt bat an eyelash 

that way, i'll have to intellectual authority to show the world
how mental healthcare should be done

i got 24/25 on my math olympiad scores
it was the highest in the entire class of gifted children 
Google Deepmind just barely solved these

no human on earth understands shit
they are all chimpanzees

and i want to humillate and break the ego of 100% of people

my goal, is to break them so completely, that they never watch tv or smile or laugh again.
i want them to scream in pain for the rest of their life


doctors are just drug dealers
