list = [
    "https://watch.thestudio.yoga/classes/elemental-pranayama",
    "https://watch.thestudio.yoga/classes/forward-into-potential",
    "https://watch.thestudio.yoga/classes/a-gentle-revival",
    "https://watch.thestudio.yoga/classes/the-universal-pulse",
    "https://watch.thestudio.yoga/classes/constructing-the-frame",
    "https://watch.thestudio.yoga/classes/full-body-breathwork",
    "https://watch.thestudio.yoga/classes/restoration-for-reformation",
    "https://watch.thestudio.yoga/classes/stable-able-and-free",
    "https://watch.thestudio.yoga/classes/functional-flow",
    "https://watch.thestudio.yoga/classes/potentiating-pigeon",
    "https://watch.thestudio.yoga/classes/warriors-create-space",
    "https://watch.thestudio.yoga/classes/the-easy-path",
    "https://watch.thestudio.yoga/classes/cross-referencing-center",
    "https://watch.thestudio.yoga/classes/atmospheric-pressure",
    "https://watch.thestudio.yoga/classes/blocks-remove-blocks",
    "https://watch.thestudio.yoga/classes/elemental-energetics",
    "https://watch.thestudio.yoga/classes/self-soother",
    "https://watch.thestudio.yoga/classes/being-in-the-moment",
    "https://watch.thestudio.yoga/classes/the-wrist-joint",
    "https://watch.thestudio.yoga/classes/recharge-and-restore",
    "https://watch.thestudio.yoga/classes/in-the-loop",
    "https://watch.thestudio.yoga/classes/embodied-orientation",
    "https://watch.thestudio.yoga/classes/elevating-our-frames",
    "https://watch.thestudio.yoga/classes/katonah-in-flow",
    "https://watch.thestudio.yoga/classes/foundations-of-a-hang",
    "https://watch.thestudio.yoga/classes/fluency-practice",
    "https://watch.thestudio.yoga/classes/whole-unto-ourselves",
    "https://watch.thestudio.yoga/classes/back-to-our-roots",
    "https://watch.thestudio.yoga/classes/the-hip-joint",
    "https://watch.thestudio.yoga/classes/hang-in-there",
    "https://watch.thestudio.yoga/classes/find-your-footing",
    "https://watch.thestudio.yoga/classes/frame-restoration",
    "https://watch.thestudio.yoga/classes/cultivating-good-soil",
    "https://watch.thestudio.yoga/classes/well-rounded-practice",
    "https://watch.thestudio.yoga/classes/five-element-practice",
    "https://watch.thestudio.yoga/classes/fold-and-spin",
    "https://watch.thestudio.yoga/classes/sleep-practice",
    "https://watch.thestudio.yoga/classes/revolving-around-center",
    "https://watch.thestudio.yoga/classes/pre-and-post-natal-essentials",
    "https://watch.thestudio.yoga/classes/circling-the-square",
    "https://watch.thestudio.yoga/classes/infinite-breath",
    "https://watch.thestudio.yoga/classes/home-renovation",
    "https://watch.thestudio.yoga/classes/unfolding-the-wave",
    "https://watch.thestudio.yoga/classes/collect-yourself",
    "https://watch.thestudio.yoga/classes/simple-and-spherical",
    "https://watch.thestudio.yoga/classes/stable-and-able",
    "https://watch.thestudio.yoga/classes/frame-of-reference",
    "https://watch.thestudio.yoga/classes/voluminous-alchemy",
    "https://watch.thestudio.yoga/classes/building-new-foundations",
    "https://watch.thestudio.yoga/classes/knee-on-the-floor-foot-in-the-wall",
    "https://watch.thestudio.yoga/classes/potentiating-into-autumn",
    "https://watch.thestudio.yoga/classes/polarity-of-presence",
    "https://watch.thestudio.yoga/classes/breathing-the-ecological-body",
    "https://watch.thestudio.yoga/classes/cassandra-simons",
    "https://watch.thestudio.yoga/classes/brima-jah",
    "https://watch.thestudio.yoga/classes/centered-circumference",
    "https://watch.thestudio.yoga/classes/the-magic-square-in-practice",
    "https://watch.thestudio.yoga/classes/elevate-your-vibration",
    "https://watch.thestudio.yoga/classes/set-sail",
    "https://watch.thestudio.yoga/classes/rinse-and-repeat",
    "https://watch.thestudio.yoga/classes/embodied-pole-practice",
    "https://watch.thestudio.yoga/classes/pranayama-slow-and-low",
    "https://watch.thestudio.yoga/classes/home-practice-recipe",
    "https://watch.thestudio.yoga/classes/origami-folding",
    "https://watch.thestudio.yoga/classes/handstand-foundations",
    "https://watch.thestudio.yoga/classes/the-tune-up",
    "https://watch.thestudio.yoga/classes/recharge-your-battery",
    "https://watch.thestudio.yoga/classes/the-eye-of-the-needle",
    "https://watch.thestudio.yoga/classes/back-bend-basics",
    "https://watch.thestudio.yoga/classes/elevate-and-expand",
    "https://watch.thestudio.yoga/classes/our-spherical-nature-with-ty",
    "https://watch.thestudio.yoga/classes/asana-for-pranayama",
    "https://watch.thestudio.yoga/classes/vibratory-stillness",
    "https://watch.thestudio.yoga/classes/empowering-angles",
    "https://watch.thestudio.yoga/classes/spherical-levity",
    "https://watch.thestudio.yoga/classes/release-and-realize",
    "https://watch.thestudio.yoga/classes/cleaning-out-the-basement",
    "https://watch.thestudio.yoga/classes/back-to-basics",
    "https://watch.thestudio.yoga/classes/division-of-three",
    "https://watch.thestudio.yoga/classes/ready-to-sprout",
    "https://watch.thestudio.yoga/classes/cleaning-up-joint-space",
    "https://watch.thestudio.yoga/classes/a-full-sphere-practice",
    "https://watch.thestudio.yoga/classes/angles-for-insight",
    "https://watch.thestudio.yoga/classes/build-stamina",
    "https://watch.thestudio.yoga/classes/potent-practice",
    "https://watch.thestudio.yoga/classes/experience-breath",
    "https://watch.thestudio.yoga/classes/cross-referencing-for-volume",
    "https://watch.thestudio.yoga/classes/gomukhasana-for-grounding",
    "https://watch.thestudio.yoga/classes/folding-for-function",
    "https://watch.thestudio.yoga/classes/winters-pattern",
    "https://watch.thestudio.yoga/classes/recipes-for-joy",
    "https://watch.thestudio.yoga/classes/traversing-the-personal-abode",
    "https://watch.thestudio.yoga/classes/simply-restorative",
    "https://watch.thestudio.yoga/classes/repetition-technique-and-time",
    "https://watch.thestudio.yoga/classes/kidneys-and-kindness",
    "https://watch.thestudio.yoga/classes/the-spit-inspiration-support",
    "https://watch.thestudio.yoga/classes/twisting-for-reflection",
    "https://watch.thestudio.yoga/classes/recharge-from-within",
    "https://watch.thestudio.yoga/classes/bedtime-wind-down",
    "https://watch.thestudio.yoga/classes/frame-work",
    "https://watch.thestudio.yoga/classes/feet-and-foundations",
    "https://watch.thestudio.yoga/classes/cultivating-contact",
    "https://watch.thestudio.yoga/classes/from-effervescence-to-depth",
    "https://watch.thestudio.yoga/classes/embodying-imagination",
    "https://watch.thestudio.yoga/classes/your-lunar-nature",
    "https://watch.thestudio.yoga/classes/organ-function",
    "https://watch.thestudio.yoga/classes/the-narrative-thread",
    "https://watch.thestudio.yoga/classes/body-scan-somatic-reset",
    "https://watch.thestudio.yoga/classes/measure-with-right-angles",
    "https://watch.thestudio.yoga/classes/accessing-plow",
    "https://watch.thestudio.yoga/classes/build-stability",
    "https://watch.thestudio.yoga/classes/be-with-your-breath",
    "https://watch.thestudio.yoga/classes/orient-yourself",
    "https://watch.thestudio.yoga/classes/find-your-spin",
    "https://watch.thestudio.yoga/classes/meditation-on-presence",
    "https://watch.thestudio.yoga/classes/the-cyclical-nature-of-practice",
    "https://watch.thestudio.yoga/classes/chairs-for-contact",
    "https://watch.thestudio.yoga/classes/measure-up",
    "https://watch.thestudio.yoga/classes/up-your-function",
    "https://watch.thestudio.yoga/classes/expand-your-capacity",
    "https://watch.thestudio.yoga/classes/stir-the-cosmic-waters",
    "https://watch.thestudio.yoga/classes/orient-to-center",
    "https://watch.thestudio.yoga/classes/hangs-for-stamina",
    "https://watch.thestudio.yoga/classes/mother-yourself",
    "https://watch.thestudio.yoga/classes/become-a-sphere",
    "https://watch.thestudio.yoga/classes/cultivating-stability",
    "https://watch.thestudio.yoga/classes/shoulder-shoulder-hip-hip",
    "https://watch.thestudio.yoga/classes/wrapping-consciousness",
    "https://watch.thestudio.yoga/classes/stoking-the-fire-of-imagination",
    "https://watch.thestudio.yoga/classes/cultivating-primal-desire",
    "https://watch.thestudio.yoga/classes/traveling-periphery",
    "https://watch.thestudio.yoga/classes/mediate-the-moment",
    "https://watch.thestudio.yoga/classes/move-in-two-directions",
    "https://watch.thestudio.yoga/classes/open-up-your-imagination",
    "https://watch.thestudio.yoga/classes/change-your-internal-atmosphere",
    "https://watch.thestudio.yoga/classes/drive-currency-with-contact",
    "https://watch.thestudio.yoga/classes/embodying-the-elements",
    "https://watch.thestudio.yoga/classes/hold-your-ground",
    "https://watch.thestudio.yoga/classes/shift-your-chemistry",
    "https://watch.thestudio.yoga/classes/lotus-for-fluency",
    "https://watch.thestudio.yoga/classes/breathe-with-imagination",
    "https://watch.thestudio.yoga/classes/set-up-your-structure",
    "https://watch.thestudio.yoga/classes/constructing-the-container",
    "https://watch.thestudio.yoga/classes/exploring-for-insight",
    "https://watch.thestudio.yoga/classes/create-more-space",
    "https://watch.thestudio.yoga/classes/playing-with-time",
    "https://watch.thestudio.yoga/classes/waking-up-the-unconscious",
    "https://watch.thestudio.yoga/classes/experience-equanimity",
    "https://watch.thestudio.yoga/classes/traverse-your-internal-landscape",
    "https://watch.thestudio.yoga/classes/an-interior-experience",
    "https://watch.thestudio.yoga/classes/articulating-the-present-moment",
    "https://watch.thestudio.yoga/classes/restorative-chairs",
    "https://watch.thestudio.yoga/classes/low-and-slow",
    "https://watch.thestudio.yoga/classes/kidney-awareness",
    "https://watch.thestudio.yoga/classes/the-alchemy-of-fire-and-water",
    "https://watch.thestudio.yoga/classes/ball-in-mitt-fit",
    "https://watch.thestudio.yoga/classes/structural-support",
    "https://watch.thestudio.yoga/classes/stable-foundations",
    "https://watch.thestudio.yoga/classes/reverse-namaste",
    "https://watch.thestudio.yoga/classes/nervous-system-soother",
    "https://watch.thestudio.yoga/classes/breath-wraps",
    "https://watch.thestudio.yoga/classes/props-to-measure",
    "https://watch.thestudio.yoga/classes/access-your-underworld",
    "https://watch.thestudio.yoga/classes/explore-the-elements",
    "https://watch.thestudio.yoga/classes/mediate-extremes",
    "https://watch.thestudio.yoga/classes/contact-for-safety",
    "https://watch.thestudio.yoga/classes/find-buoyancy",
    "https://watch.thestudio.yoga/classes/a-pigeon-both-ways",
    "https://watch.thestudio.yoga/classes/contact-for-leverage",
    "https://watch.thestudio.yoga/classes/find-your-fit",
    "https://watch.thestudio.yoga/classes/mine-your-depths",
    "https://watch.thestudio.yoga/classes/sustaining-practice",
    "https://watch.thestudio.yoga/classes/open-your-windows",
    "https://watch.thestudio.yoga/classes/prenatal-practice",
    "https://watch.thestudio.yoga/classes/expanding-potential",
    "https://watch.thestudio.yoga/classes/forward-bending",
    "https://watch.thestudio.yoga/classes/generate-heat",
    "https://watch.thestudio.yoga/classes/hip-joint-folds",
    "https://watch.thestudio.yoga/classes/lunar-solar-stellar",
    "https://watch.thestudio.yoga/classes/lung-expansion",
    "https://watch.thestudio.yoga/classes/the-threading-self",
    "https://watch.thestudio.yoga/classes/magic-square-pranayama",
    "https://watch.thestudio.yoga/classes/scale-your-heights",
    "https://watch.thestudio.yoga/classes/habits-and-propensities",
    "https://watch.thestudio.yoga/classes/longevity-practice",
    "https://watch.thestudio.yoga/classes/playing-with-chairs",
    "https://watch.thestudio.yoga/classes/the-primary-fold",
    "https://watch.thestudio.yoga/classes/engage-imagination",
    "https://watch.thestudio.yoga/classes/multitask-to-maximize",
    "https://watch.thestudio.yoga/classes/grace-and-effort",
    "https://watch.thestudio.yoga/classes/potentiate-yourself",
    "https://watch.thestudio.yoga/classes/shoulder-stand-set-up",
    "https://watch.thestudio.yoga/classes/the-game-of-time",
    "https://watch.thestudio.yoga/classes/release-personal-investment",
    "https://watch.thestudio.yoga/classes/articulate-your-wave",
    "https://watch.thestudio.yoga/classes/kidney-energy",
    "https://watch.thestudio.yoga/classes/deep-hip-opener",
    "https://watch.thestudio.yoga/classes/move-your-waters",
    "https://watch.thestudio.yoga/classes/yoga-as-origami",
    "https://watch.thestudio.yoga/classes/light-your-pilot-light"
]


import requests
import base64
from tqdm import tqdm


master_json_url = 'https://178skyfiregce-a.akamaihd.net/exp=1474107106~acl=%2F142089577%2F%2A~hmac=0d9becc441fc5385462d53bf59cf019c0184690862f49b414e9a2f1c5bafbe0d/142089577/video/426274424,426274425,426274423,426274422/master.json?base64_init=1'
base_url = master_json_url[:master_json_url.rfind('/', 0, -26) + 1]

resp = requests.get(master_json_url)
content = resp.json()

heights = [(i, d['height']) for (i, d) in enumerate(content['video'])]
idx, _ = max(heights, key=lambda (_, h): h)
video = content['video'][idx]
video_base_url = base_url + video['base_url']
print 'base url:', video_base_url

filename = 'video_%d.mp4' % video['id']
print 'saving to %s' % filename

video_file = open(filename, 'wb')

init_segment = base64.b64decode(video['init_segment'])
video_file.write(init_segment)

for segment in tqdm(video['segments']):
    segment_url = video_base_url + segment['url']
    resp = requests.get(segment_url, stream=True)
    if resp.status_code != 200:
        print 'not 200!'
        print resp
        print segment_url
        break
    for chunk in resp:
        video_file.write(chunk)

video_file.flush()
video_file.close()